<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Edit Question</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" onload="start();">
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1></h1>
		<a id="BackHyperLink" href="../../trainer.php">Back</a>
		<form id="form_118102" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Edit Question</h2>
			<p>Specify the question. Replace numbers with variables.</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="qtext">Question </label>
		<div>
			<textarea id="qtext" name="qtext" class="element textarea small"></textarea> 
		</div><p class="guidelines" id="guide_1"><small>Question, enclose variables in double hash ##X##</small></p> 
		</li>		<li id="li_2" >
		<label class="description" for="qAnswerFormula">Formula to find answer </label>
		<div>
			<textarea id="qAnswerFormula" name="qAnswerFormula" class="element textarea small"></textarea> 
		</div><p class="guidelines" id="guide_2"><small>Prepare JavaScript statement, enclose variables in double hash ##X##</small></p> 
		</li>
				<input type="hidden" name="ssuid" id="ssuid" value="0" />	
				<input type="hidden" name="qid" id="qid" value="0" />
					<li class="buttons">
				<input type="hidden" name="form_id" value="118102" />
			    
				<input id="saveForm" class="button_text" type="button" name="submit" value="Submit" onClick="SaveFormData('BackHyperLink', 'form_118102', 'DivSaveFormDataAsQuestion', 'qid');" />
		</li>
			</ul>
		</form>	

		<div id="DivSaveFormDataAsQuestion" style="display:none">
        {
			"url":"/pJSON/SQLite3/question/question-edit-row.php",
            "payload":{
                "action":"SaveFormDataAndUpdateRowGetRowID"
            }
        }
    	</div>
		<div id="DivDisplayQuestion" style="display:none">
        {
            "url":"/pJSON/SQLite3/question/question-get.php",
            "payload":{
                "formID":"form_118102",
				"action":"QueryData"
            },
            "formelements":{
				"ssuid":"hidden",
				"qid":"hidden",
				"qtext":"textarea",
				"qAnswerFormula":"textarea"
            }			
        }
    	</div>   		
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
	<script src="../../js/subjectrainerjsfile/jquery-3.5.1.min.js"  crossorigin="anonymous"></script>
	<script src="../../js/subjectrainerjsfile/st.js"  crossorigin="anonymous"></script>
	
    <script> 
    function start(){
		SetBackURL("BackHyperLink","./question-view.php");
		SetQuestionIDInHiddenField("ssuid");
		SetQuestionIDInHiddenField("qid");
		DisplayDataInFrom("DivDisplayQuestion");
	}
    </script>	
</html>