<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Add Question Variable</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" onload="start();">
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1></h1>
		<a id="BackHyperLink" href="#">Back</a>        
		<form id="form_118102" class="appnitro"  method="post" action="">
			<div class="form_description">
				<h2>Add Question Variable</h2>
				<p>Add variables used inside the question</p>
			</div>						
			<ul >
				
				<li id="li_1" >
					<label class="description" for="vPlaceHolder">Variable Name </label>
					<div>
						<input id="vPlaceHolder" name="vPlaceHolder" class="element text medium" type="text" maxlength="255" value=""/> 
					</div><p class="guidelines" id="guide_1"><small>Variable used inside the question text as well as answer formula.</small></p> 
				</li>		
			
				<li id="li_2" >
					<label class="description" for="vType">Variable Type </label>
					<div>
					<select class="element select medium" id="vType" name="vType"> 
						<option value=""></option>
						<option value="Number" >Number</option>
						<option value="Text" >Text</option>
					</select>
					</div><p class="guidelines" id="guide_2"><small>Select number if the variable represents a number</small></p> 
				</li>

				<input type="hidden" name="qvid" id="qvid" value="0" />	
				<input type="hidden" name="qid" id="qid" value="0" />	
				

				<li class="buttons">					
					<input id="saveForm" class="button_text" type="button" name="Save" value="Save" onClick="SaveFormData('BackHyperLink', 'form_118102', 'DivSaveFormDataAsQuestion', 'qvid');" />

					<input id="deleteForm" class="button_text" type="button" name="Delete" value="Delete" onClick="SaveFormData('BackHyperLink', 'form_118102', 'DivDeleteFormDataAsQuestion', 'qvid');" />
					<input type="hidden" name="actiondelete" id="actiondelete" value="0" />	

				</li>

			</ul>
		</form>	

		<div id="DivSaveFormDataAsQuestion" style="display:none">
        {
			"url":"/pJSON/SQLite3/question/question-variable-add-new-row.php",
			"action":"SaveFormDataAndGetNewRowID",
            "payload":{
                "action":"SaveFormDataAndGetNewRowID"
            }
        }
    	</div>

		<div id="DivDeleteFormDataAsQuestion" style="display:none">
        {
			"url":"/pJSON/SQLite3/question/question-variable-add-new-row.php",
			"action":"SaveFormDataAndGetNewRowID",
            "payload":{
                "action":"SaveFormDataAndGetNewRowID"
            },
            "alterpayload":{
                "actiondelete":1
            }  
        }
    	</div>		

		<div id="DivDisplayQuestionVariable" style="display:none">
        {
            "url":"/pJSON/SQLite3/question/question-variable-get.php",
            "payload":{
                "formID":"form_118102",
				"action":"QueryData"
            },
            "formelements":{
				"qvid":"hidden",
				"qid":"hidden",
				"vPlaceHolder":"text",
				"vType":"select"
            }			
        }
    	</div>  
		
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
	<script src="../../js/subjectrainerjsfile/jquery-3.5.1.min.js"  crossorigin="anonymous"></script>
	<script src="../../js/subjectrainerjsfile/st.js"  crossorigin="anonymous"></script>
	
    <script> 
    function start(){
		SetBackURLNoQueryString("BackHyperLink","javascript:window.opener.windowReload();window.close();");
		SetIDInHiddenField("qid");
		SetIDInHiddenField("qvid");
		DisplayDataInFrom("DivDisplayQuestionVariable");
	}

    </script>	
</html>